#' Aggregate the results from a logRegCV() run
#'
#' @description Combines the results from a list generated by logRegCV() into a matrix. Useful for making summary plots.
#'
#' @param logRegCV.object A list object generated by logRegCV()
#' @param var A character string of what information to return. 'lambda.min': lambda values with the lowest error, 'lambda.1se':
#' lambda value one standard error higher than lambda.min, 'coef': regression coefficients, 'pred': probabilities from predictions
#' on the outer fold test sets
#'
#' @return Returns a vector/matrix of the selected result type
#' @export
#'
#' @examples
#' ## Extract lambda.min
#' aggregateLogRegCV(lrCV, 'lambda.min')
#'
#' ## Extract multiple result types
#' lapply(c('lambda.min','coef','pred'), function(i){ aggregateLogRegCV(lrCV, i) })

aggregateLogRegCV <- function(logRegCV.object, var)
{
   ## lambda
   if(var == 'lambda.1se'){
      output <- sapply(logRegCV.object, function(fold){ fold$logReg[['lambda.1se']] })
   } else if (var == 'lambda.min'){
      output <- sapply(logRegCV.object, function(fold){ fold$logReg[['lambda.min']] })
   }

   ## coef
   else if(var == 'coef'){
      output <- lapply(logRegCV.object, function(fold){ fold$logReg %>% coef() }) %>% do.call(cbind,.) %>% as.matrix() %>% as.data.frame()
      colnames(output) <- 1:ncol(output)
   }

   ## pred
   else if(var == 'pred'){
      output <- lapply(logRegCV.object, function(outerFold){ outerFold$pred }) %>% do.call(rbind,.) %>% .[order(rownames(.)),]
   }

   return(output)
}
