#' Aggregate the results from a randomForestCV() run
#'
#' @param randomForestCV.object A list object generated by randomForestCV()
#' @param var A character string of what information to return. 'importance': MeanDecreaseAccuracy, 'pred': probabilities
#' from predictions
#'
#' @return Returns a dataframe/matrix of the selected result type
#' @export
#'
#' @examples
#' ## Extract MeanDecreaseAccuracy
#' aggregateLogRegCV(rfCV, 'importance')
#'
#' ## Extract multiple result types
#' lapply(c('importance','pred'), function(i){ aggregateRandomForestCV(rfCV, i) })

aggregateRandomForestCV <- function(randomForestCV.object, var)
{
   ## MeanDecreaseAccuracy
   if(var == 'importance'){
      output <-
         lapply(randomForestCV.object, function(i){ i$RF %>% importance(.,type=1) }) %>% do.call(cbind,.) %>% as.data.frame()
      colnames(output) <- 1:ncol(output)
   }

   ## Prediction probabilities
   else if (var == 'pred'){
      output <-
         lapply(randomForestCV.object, function(i){ i$pred }) %>%
         do.call(rbind,.) %>%
         .[order(rownames(.)),]
   }

   return(output)
}
