#' Aggregate the results from a randomForestCV() run
#'
#' @param randomForestCV.object A list object generated by randomForestCV()
#' @param var A character string of what information to return. 'mdg': MeanDecreaseGini, 'mda': MeanDecreaseAccuracy, 'pred': probabilities
#' from predictions
#'
#' @return Returns a dataframe/matrix of the selected result type
#' @export
#'
#' @examples
#' ## Extract MeanDecreaseAccuracy
#' aggregateLogRegCV(rfCV, 'mda')
#'

aggregateRandomForestCV <- function(randomForestCV.object, var)
{
   ## MeanDecreaseGini
   if(var == 'mdg'){
      output <-
         lapply(randomForestCV.object, function(i){ i$RF %>% importance(.,type=2) }) %>% do.call(cbind,.) %>% as.data.frame()
      colnames(output) <- 1:ncol(output)
      class(output) <- c(class(output),'mdg')
   }
   
   ## MeanDecreaseAccuracy
   if(var == 'mda'){
      output <-
         lapply(randomForestCV.object, function(i){ i$RF %>% importance(.,type=1) }) %>% do.call(cbind,.) %>% as.data.frame()
      colnames(output) <- 1:ncol(output)
      class(output) <- c(class(output),'mda')
   }

   ## Prediction probabilities
   else if (var == 'pred'){
      output <-
         lapply(randomForestCV.object, function(i){ i$pred }) %>%
         do.call(rbind,.) %>%
         .[order(rownames(.)),]
   }

   return(output)
}
